background_opacity 0.85
hide_window_decorations yes
confirm_os_window_close 0
font_family      monospace
font_size        11.0
window_padding_width 10

background            #4b3d61
foreground            #fbcce3
cursor                #fbcce3
cursor_text_color     #4b3d61
selection_background  #665482
selection_foreground  #ffffff

color0  #4b3d61
color8  #665482
color1  #f19a9a
color9  #f19a9a
color2  #b8e9c0
color10 #b8e9c0
color3  #f9e3b4
color11 #f9e3b4
color4  #a38df4
color12 #c1b3f9
color5  #fbcce3
color13 #fbcce3
color6  #a7e8f0
color14 #a7e8f0
color7  #e0def4
color15 #ffffff
